server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/expense_tracker
    username: root
    password: Welcome@23
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    username: expensetracker277@gmail.com
    password: exgzzsljlekaglgb
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    com.expense.tracker.expense.tracker.backend: DEBUG



